### ISSUE TITLE
Support negative offset

### ISSUE THREAD

**Issue by roidelapluie** [prometheus-community/codemirror-promql#114]
PromQL now supports `offset -1h`

**Comment by Nexucis** [comment]
mmm I guess I did something wrong, but when I tried with the master version of Prometheus through netlify, I have an error returned by the server:

https://prometheus-react.netlify.app/graph?g0.expr=foo%20offset%20-1h&g0.tab=1&g0.stacked=0&g0.range_input=1h

![image](https://user-images.githubusercontent.com/4548045/112276737-5afafc80-8c81-11eb-9263-a9797223616d.png)

Don't know where I'm wrong :/

**Comment by roidelapluie** [comment]
That feature is not enabled by default and  new in the incoming prometheus
2.26 :)

Le mer. 24 mars 2021 à 09:15, Augustin Husson ***@***.***> a
écrit :

**Comment by Nexucis** [comment]
reopen the issue as long as lezer is not upgraded into codemirror

**Comment by roidelapluie** [comment]
This is sooooo confusing to know where we need to open issues

**Comment by Nexucis** [comment]
yeah I know :(. 

And it can become worse once users will use it in Prometheus, they will open issue in Prometheus directly, not here.

But actually it's not so bad that you opened the issue here since it's a bit the front-end of lezer-promQL, + in this particular case, I had to fix the issue directly in the grammar, but potentially it can have a fix here as well. 

It's part of the investigation to know at which level the issue should be fixed, not part of the user to know where to open the issue. But that's just my opinion ^^

**Comment by juliusv** [comment]
Yeah, and as @roidelapluie suggested earlier, we can think about moving everything into the Prometheus repo in the long run. But I'd like us to gain a bit more experience with it before making that decision. In the end, this editor is not tied to the Prometheus repo only (also PromLens, and can be used by other people), except for the fact that the Go PromQL engine is also in the Prometheus repo, and so it would enable making a single PR that changes both the PromQL engine and the CodeMirror support.

**Comment by Nexucis** [comment]
maybe a first move, could be to transfer the repo (lezer + codemirror) to the Prometheus org no ? I think @roidelapluie was suggesting that too.

And this is a quite an easy move I think no ?

**Comment by Nexucis** [comment]
even if I didn't really get what does it change. But it seems @roidelapluie was thinking differently. So I suppose it change something

**Comment by juliusv** [comment]
Yeah, just moving orgs doesn't help much, the benefit would come from having things in the same repo, so they can be changed at once in a single PR.

**Comment by Nexucis** [comment]
I understood it is important to have the lezer PromQL grammar synchronized with the mainstream grammar. And yeah it can makes sense actually that lezer-promql is provided directly by Prometheus.

But for codemirror, IMO it can live independently of the changes in Prometheus. Since it's "just" a wrapper of lezer to provide more functionalities than the raw grammar  and the functionalities provided by this lib are not really bound to the changes performed in Prometheus.

And I think being able to synchronize the mainstream promQL grammar and the lezer one would be already a big change (In term of release / version management, contribution, ownership ...etc.)

**Comment by juliusv** [comment]
@Nexucis The promql-codemirror logic can be quite dependent on lezer-promql though, no? Sure, it won't change quite as much, but if one wants to make sure that everything needed for a PromQL change in Prometheus can be done in a single PR, then it could make sense to have that in prometheus/prometheus as well. I'm not saying we should do all that overall yet, but at least the same argument applies IMO.

**Comment by Nexucis** [comment]
yeah you are right :)
