### ISSUE TITLE
Remove strict node requirement

### ISSUE THREAD

**Issue by dsmith3197** [prometheus-community/codemirror-promql#129]
Hey Julius and Augustin,

Would it be possible to remove the node version requirement in package.json or to decrement it to 12?
```
  "engines": {
    "node": ">=14.0.0"
  }
```

I'm attempting to consume `codemirror-promql` in a yarn monorepo and am running into issues due to conflicting node versions.

I know [codemirror.next](https://github.com/codemirror/codemirror.next) says that it requires node 14 in the README, but I believe that is only necessary for the development server.  In particular, you can see in the [change log](https://codemirror.net/6/docs/changelog/) that the library works on node 12 and 13 as well.

> The packages are no longer available as CommonJS files. To run the code on node.js, you'll need node 13 or pass --experimental-modules to node 12.

**Comment by dsmith3197** [comment]
Also, it'd be great if we could add a CommonJS module to the build.  CodeMirror added back CommonJS support in version 0.17.1.  I'm happy to help out making these changes.

**Comment by Nexucis** [comment]
Hey Doug :),

So yes we can decrease the version to v12, I already tried when we integrated cm-promql in Prometheus and it works well. (https://github.com/prometheus-community/codemirror-promql/pull/112).

I guess I can reopen this PR and then merge it.

And definitely supporting CommonJS files would be great. The main reason it didn't support it was because codemirror wasn't and it causes some issue when running the tests. So that's why the lib was only supporting esm package.

As long as codemirror is supporting it, there is no reason to not do it as well here. + It will ease the integration in Prometheus/Thanos by removing planty of crappy workaround.

And same as codemirror, we should still support esm. Which is a requirement for a good integration in Angular

Let us know if you want to work on supporting CommonJS :)

**Comment by dsmith3197** [comment]
Thanks! Decreasing to node 12 would be fantastic.  I can make a PR to add CommonJS support 👍🏻

**Comment by Nexucis** [comment]
alright :). NodeJS version is decreased to v12 through the PR #112 that I just merged.

Looking forward for the CommonJS support ;)

**Comment by dsmith3197** [comment]
I just made a PR adding CommonJS #130

**Comment by Nexucis** [comment]
fix thanks to #130 & #112

**Comment by dsmith3197** [comment]
@Nexucis any chance you could cut a new version soon?

**Comment by Nexucis** [comment]
yes, I will create the PR to update the `package.json` and the `Changelog`. Then it should be merged quite fast

**Comment by Nexucis** [comment]
PR is #135. Once it is merged, then we should be able to release it.

**Comment by Nexucis** [comment]
it's released @dsmith3197 sorry for the long delay to do it.

**Comment by dsmith3197** [comment]
No worries, thanks so much @Nexucis :)
