### ISSUE TITLE
Snippets don't get applied correctly when selecting them via the mouse

### ISSUE THREAD

**Issue by juliusv** [prometheus-community/codemirror-promql#25]
When selecting a snippet such as `sum(rate(<input vector>[5m]))` with the mouse (not the keyboard), the snippet text is inserted verbatim, without `<input vector>` becoming a tabbable/completable field.

**Comment by Nexucis** [comment]
maybe an upgrade of CMN to v0.10.0 will fix the issue.

**Comment by Nexucis** [comment]
Problem is still there after the upgrade to CMN v0.10.0.
We should try with the vanilla app to see if the issue is only on our side or on cmn side too.

**Comment by dvkndn** [comment]
Hi I did some more experiments, hope this helps:

1. The problem is still there (in codemirror-promql) after upgrade to CMN 0.12
2. The problem also exists on https://codemirror.net/6/ but it's a little bit different. You can see in the screenshot below that the placeholder part is selected but the editor is no longer focused. I believe this is a bug in CM

![Screenshot from 2020-09-20 03-42-34](https://user-images.githubusercontent.com/5953369/93688926-f903e380-faf3-11ea-92b7-5f2b75c0ee46.png)

This is different than codemirror-promql where there is no text selected at all (the editor still lost its focus though)

**Comment by dvkndn** [comment]
Related: https://github.com/codemirror/codemirror.next/issues/287

**Comment by juliusv** [comment]
@dvkndn Awesome, thanks for the testing and reporting it on the CMN side!

**Comment by dvkndn** [comment]
Hey guys this is fixed upstream :D https://github.com/codemirror/codemirror.next/commit/c4ce6ee7bc6ac2b310bb63d74fb42cd90891cfe5 let me test it when CMN releases a new version

**Comment by juliusv** [comment]
@dvkndn Nice! And since it's in the tooltip plugin and not our autocomplete plugin fork, it will hopefully just work for us as well. (it would still be nice if we didn't need our autocomplete plugin fork in the long term)
