### ISSUE TITLE
Clarify the difference between Prometheus and LSP mode

### ISSUE THREAD

**Issue by dvkndn** [prometheus-community/codemirror-promql#46]
I mean this :D (and the linter too)

> Note: The auto-completion feature has 3 different modes, each requiring a different setup

~My wild guess is that the LSP is better than the Prometheus mode? But honestly I can't find an example (my queries are pretty basic so I see no difference between them). I understand that setting up LSP is more difficult than Prometheus mode though.~

Actually now I think that Prometheus mode is better... in LSP I can't get the function (e.g. "rate", "sum") suggestions but I do in Premetheus mode

Related PRs I found:
- https://github.com/prometheus-community/codemirror-promql/pull/29
- https://github.com/prometheus-community/codemirror-promql/pull/9
- https://github.com/prometheus-community/codemirror-promql/pull/5

**Comment by dvkndn** [comment]
I'm more than happy to help :D I can update the README if I know the difference

**Comment by Nexucis** [comment]
For the autocompletion mode:
* You have the LSP mode which used the endpoint exposed by the server [promql-langserver](https://github.com/prometheus-community/promql-langserver) for the autocompletion list.
* You have the Prometheus mode which is more or less the same than what LSP is proposing by using the native Prometheus API
* And you have the Offline mode which only proposed the PromQL keyword. It's used when there is no distant server available. You can consider it's the fallback mode when others didn't work.

I don't think it's accurate to say you have a mode that is better than another one. Each of them are still under construction and need to be improved. And each of them are proposing different option and setup according to your environment

Retarding the linter it's for the moment quite experimental. You have:
* The LSP mode ( same as the autocompletion)
* The Offline mode which is more or less a transcription of the PromQL parser you can find in the Prometheus code

Note that PR are always welcomed and if you think the Readme is not really up to date, it's just because the API exposed by this project is changing regularly. If you are looking at the release note you will see we made a lot of breaking change :).

I hope it clarify a bit the diff + what is going on. If you still want to make a PR, then I will be happy to review it once I'm back from holidays.

**Comment by dvkndn** [comment]
Thank you. It's very clear. If you guys are busy I'll try to keep the README update for you :D 

Also sorry for bothering you in your holiday! Hope you are having a great one!

**Comment by Nexucis** [comment]
> Also sorry for bothering you in your holiday! Hope you are having a great one!

Oh don't worry you don't bother me. I was just passing here. You were just lucky I saw your issue a couple hours after you opened it hahaha

**Comment by Nexucis** [comment]
And like I said, PR are always welcomed. So if you want to do so, then go ahead :)
