### ISSUE TITLE
Incorrect linter errors when whitespace around binops is missing

### ISSUE THREAD

**Issue by juliusv** [prometheus-community/codemirror-promql#69]
Try `a+b`, it gives a linter error for `b`. `a+ b` works though. Autocomplete seems to work in all cases, so not sure it's a lezer grammar bug or just a linter bug.

**Comment by Nexucis** [comment]
it's a problem with the method `walkThrough` that doesn't find the node corresponding to `b`. 
It's used here: https://github.com/prometheus-community/codemirror-promql/blob/master/src/lang-promql/parser/parser.ts#L300

It's linked to this issue and comment: https://github.com/codemirror/codemirror.next/issues/270#issuecomment-704420758

For this particular case, it doesn't really to have the `Subtree` corresponding to `b`, it's just need to have the start/end position. So it's still possible to create another method that returns these information instead of trying to find the node and failed to find it
