### ISSUE TITLE
Support `bool` in autocompletion

### ISSUE THREAD

**Issue by juliusv** [prometheus-community/codemirror-promql#89]
In `foo > bool 1`, the `bool` is not yet autocompleted.

**Comment by Nexucis** [comment]
bool could be autocompleted once  `1` is written. Otherwise if it is autocompleted every time it could lead to a promQL error.
Like for example, if instead of `1` the user would like to write `bar` instead, then you will have a wrong promQL query afterwards.

Are you agree to autocomplete `bool` only once you have the left (`foo`) and right (`1`) expression available ?

**Comment by juliusv** [comment]
If a user just types an expression from beginning to end normally, it would be a bit useless if it only got autocompleted after we have the `1`. And `bool` is actually valid between any scalar/vector type combinations (even `2 == bool 2`), as long as the operator is a comparison operator.

So I would say, we should autocomplete it directly after a comparison operator.
